spring:
  application:
    name: notify-hub
  datasource:
    url: jdbc:postgresql://localhost:15432/notify_hub
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: public
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
